name: Trivy Scan (reusable)
on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: "."

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy filesystem scan
        run: |
          trivy fs --severity HIGH,CRITICAL ${{ inputs.path }}
